window.configuration = {
  active: 0,
  orderBy: "F",
  toggledBar: "",
  // showFullAxis: false,
  // showExpandButton: [true, false, false, true, false, true],
  // yAxisStartFrom: [30, 0, 0, 30, 0, 50],
  data: {
    url_dev: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_acc: "//www.acceptance.ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_prod: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_local: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    year: "2019",
    sex: [
      { id: "0", abbr: "M", label: "Male" },
      { id: "1", abbr: "F", label: "Female" },
    ],
    countriesEu: ["EU27_2020"],
    countriesOthers: [
      [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],[
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],[
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],
[
      "AT",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],
[
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],


    ],
    countriesNonMembers: [], /* "UK" */
    countriesEfta: ["NO", "IS"],
    paramObj: [
      {
        // geo: 'dynamically constructed',
        // sex: 'dynamically constructed',
        age: "Y_GE18",
        unit: "PC",
        isced11: "TOTAL",
        frequenc: "WEEK",
        time: "2019",
      },
      {
        age: "Y_GE18",
        unit: "PC",
        isced11: "TOTAL",
        smoking: "SM_DAY",
        time: "2019",
      },
      {
        age: "TOTAL",
        unit: "PC",
        isced11: "TOTAL",
        n_portion: "1-4",
        time: "2019",
      },
      {
        age: "TOTAL",
        unit: "PC",
        isced11: "TOTAL",
        duration: "MN_GE150",
        time: "2014",
      },
      {
        age: "TOTAL",
        unit: "PC",
        isced11: "TOTAL",
        bmi: ["BMI25-29", "BMI_GE30"], //values will get sum up!
        time: "2019",
      }
    ],
    dataUrlMapping: [0, 1, 2, 3, 4], //which rawdata/url to use for the different categories
    lang: "en",
    bookmarkLink_0:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/215eb9eb-2090-46da-906d-dc44f70e9692?lang=en",
    bookmarkLink_1:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/d3056e76-dac4-41ed-b0cb-8a56c137e390?lang=en",
    bookmarkLink_2:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/91ea779b-c29a-4a5c-96d6-7177c1af2aba?lang=en",
    bookmarkLink_3:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/55770c77-8d85-4316-9730-c58e1138c346?lang=en",
    bookmarkLink_4:
      " https://ec.europa.eu/eurostat/databrowser/bookmark/5b198e91-3813-4370-ad24-d9214e1915ec?lang=en",
    dataUrls: [
      "hlth_ehis_al1e?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=Y_GE18&frequenc=WEEK",
      "hlth_ehis_sk1e?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&smoking=SM_DAY&age=Y_GE18",
      "hlth_ehis_fv3e?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&n_portion=1-4",
      "hlth_ehis_pe2e?time=2014&sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&duration=MN_GE150",
      "hlth_ehis_bm1e?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&bmi=BMI25-29&bmi=BMI_GE30",
    ],
  },
};

