window.configuration = {
  active: 0,
  orderBy: "F",
  toggledBar: "",
  // showFullAxis: false,
  // showExpandButton: [true, false, false, true, false, true],
  // yAxisStartFrom: [30, 0, 0, 30, 0, 50],
  data: {
    url_dev: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_acc: "//www.acceptance.ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_prod: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_local: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    year: "2018",
    sex: [
      { id: "0", abbr: "M", label: "Male" },
      { id: "1", abbr: "F", label: "Female" },
    ],
    countriesEu: ["EU27_2020"],
    countriesOthers: [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],
    countriesNonMembers: [], /*"UK"*/
    countriesEfta: ["NO", "CH", "LI"],
    paramObj: [
      {
        // geo: 'dynamically constructed',
        // sex: 'dynamically constructed',
        unit: "RT",
        age: "TOTAL",
        time: "2018",
        icd10: "C",
      },
      {
        unit: "RT",
        age: "TOTAL",
        time: "2018",
        icd10: "I20-I25",
      },
      {
        unit: "RT",
        age: "TOTAL",
        time: "2018",
        icd10: "I60-I69",
      },
    ],
    dataUrlMapping: [0, 0, 0], //which rawdata/url to use for the different categories
    lang: "en",
    bookmarkLink:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/482acbbd-68b8-4110-94cb-7c759920432b?lang=en&page=time:2018",
    dataUrls: [
      "hlth_cd_asdr2?sex=F&sex=M&precision=1&unit=RT&age=TOTAL&icd10=C&icd10=I20-I25&icd10=I60-I69&time=2017&time=2018",
    ],
  },
};

