window.configuration = {
  active: 0,
  orderBy: "F",
  toggledBar: "",
  // showFullAxis: false,
  // showExpandButton: [true, false, false, true, false, true],
  // yAxisStartFrom: [30, 0, 0, 30, 0, 50],
  data: {
    url_dev: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_acc: "//www.acceptance.ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_prod: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    url_local: "//ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/",
    year: "2015",
    sex: [
      { id: "0", abbr: "M", label: "Male" },
      { id: "1", abbr: "F", label: "Female" },
    ],
    countriesEu: ["EU27_2020"],
    countriesOthers: [
      "AT",
      "BE",
      "BG",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "EL",
      "ES",
      "FI",
      "FR",
      "HR",
      "HU",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SE",
      "SI",
      "SK",
    ],
    countriesNonMembers: [], /* "UK" */
    countriesEfta: ["NO", "CH", "IS"],
    paramObj: [
      {
        // geo: 'dynamically constructed',
        // sex: 'dynamically constructed',
        unit: "PC",
        isced11: "TOTAL",
        time: "2015",
        age: "Y_GE16",
        frequenc: "SEV_M",
        ind_type: "FRD",
      },
      {
        unit: "PC",
        isced11: "TOTAL",
        time: "2015",
        age: "Y_GE16",
        frequenc: "1-3",
        acl00: "AC521",
      },
      {
        unit: "PC",
        isced11: "TOTAL",
        time: "2015",
        age: "Y_GE16",
        frequenc: "1-3",
        acl00: "AC522A",
      },
      {
        unit: "PC",
        isced11: "TOTAL",
        time: "2015",
        age: "Y_GE16",
        frequenc: "1-3",
        acl00: "AC523H",
      },
      {
        unit: "PC",
        isced11: "TOTAL",
        time: "2015",
        age: "Y_GE16",
        frequenc: "1-3",
        acl00: "AC525",
      },
    ],
    dataUrlMapping: [0, 1, 1, 1, 1], //which rawdata/url to use for the different categories
    lang: "en",
    bookmarkLink_0:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/6014cfbc-c2e7-4108-af53-4f690d5c2845?lang=en",      
    bookmarkLink_1:
      "https://ec.europa.eu/eurostat/databrowser/bookmark/b1b25d1e-619c-446d-8668-7c7edda6e43d?lang=en",
    dataUrls: [
      "ilc_scp09?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=Y_GE16&frequenc=SEV_M&ind_type=FRD",
      "ilc_scp03?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=Y_GE16&frequenc=1-3&acl00=AC521&acl00=AC522A&acl00=AC523H&acl00=AC525",
      // 'ilc_scp03?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&n_portion=1-4',
      // 'ilc_scp03?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&duration=MN_GE150',
      // 'ilc_scp03?sex=F&sex=M&precision=1&unit=PC&isced11=TOTAL&age=TOTAL&bmi=BMI25-29&bmi=BMI_GE30'
    ],
  },
};

